FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy full project (includes fabric/ and src/)
COPY . .

RUN npm run build

RUN mkdir -p dist/fabric && cp fabric/connection-org1.json dist/fabric/ && \
    mkdir -p dist/crypto && cp -r fabric/crypto dist/crypto/

RUN node dist/scripts/importIdentity.js

EXPOSE 3000
CMD ["node", "dist/server.js"]
